### ISSUE TITLE
feat: support for sitemap in .yml files with Nuxt Content

### ISSUE THREAD

**Issue by michaelreinhard1** [harlan-zw/nuxt-seo#445]
### 🆒 Your use case

Hi, I'm using Nuxt Content and would like to add sitemap to my `.yml` files. This works as expected in `.md` files, but when I add sitemap fields to a `.yml` file, it doesn't seem to work.

### 🆕 The solution you'd like

```
sitemap:
  lastmod: 2025-05-13

```
etc.

**Comment by harlan-zw** [comment]
Hmm strange. I tried to replicate this, and it was working correctly, see https://github.com/nuxt-modules/sitemap/commit/328f611b6c7acf26579334367fe741e3a1adbd86.

```yml
# /test-yaml.yml
title: Test YAML Content
description: This is a test YAML file for sitemap
sitemap:
  lastmod: 2025-05-13
  changefreq: monthly
  priority: 0.8
content: This is some YAML content
```

![Image](https://github.com/user-attachments/assets/ae72e965-35e0-4176-be5f-b22416cc0998)

Maybe an issue with how you've configured your content.config.ts?
